import { Achievement, AchievementState, AchievementType, ActionTypes } from './types';
import KanufahrtDschungel from '../../assets/images/achievements/KanufahrtDschungel.png';
import ExampleStreakImage from '../../assets/images/achievements/example_streak_image.png';
import ExampleStreakImageRecord from '../../assets/images/achievements/example_streak_image_record.png';
import SequenceExample00 from '../../assets/images/achievements/Sequence_Example_00.png';
import SequenceExample01 from '../../assets/images/achievements/Sequence_Example_01.png';
import SequenceExample04 from '../../assets/images/achievements/Sequence_Example_04.png';

const achievements: Achievement[] = [
    {
        name: '5 erreichte Meilensteine',
        subtitle: 'Projektfortschritt',
        description: 'Ein Beispieltext für diesen Meilenstein...',
        image: SequenceExample01,
        alternativeText: 'Ein Beispielbild',
        achievedAt: '2023-09-15T12:30:00Z',
        achievedText: 'Hervorragende Leistung! Ziel erreicht.',
        actionType: ActionTypes.ACTION,
        achievementType: AchievementType.SEQUENTIAL,
        maxSteps: 4,
        currentStep: 1,
        achievementState: AchievementState.ACTIVE,
    },
    {
        name: '10 abgeschlossene Schulungseinheiten',
        subtitle: 'Weiterbildung',
        description: 'Ein Beispieltext für diese Schulungseinheit...',
        image: KanufahrtDschungel,
        alternativeText: 'Ein Beispielbild',
        achievedAt: '2023-11-05T15:45:00Z',
        achievedText: 'Herzlichen Glückwunsch! Schulung erfolgreich abgeschlossen.',
        actionType: ActionTypes.WAIT,
        achievementType: AchievementType.TIERED,
        maxSteps: 10,
        currentStep: 7,
        achievementState: AchievementState.ACTIVE,
    },
    {
        name: '20 Stunden Teamzusammenarbeit',
        subtitle: 'Kollaboration',
        description: 'Ein Beispieltext für diese Teamzusammenarbeit...',
        image: ExampleStreakImage,
        alternativeText: 'Ein Beispielbild',
        achievedAt: '2023-10-02T09:20:00Z',
        achievedText: 'Teamwork macht den Traum wahr! Tolle Zusammenarbeit.',
        actionType: ActionTypes.APPOINTMENT,
        achievementType: AchievementType.STREAK,
        maxSteps: 20,
        currentStep: 15,
        achievementState: AchievementState.ACTIVE,
    },
    {
        name: '15 erfolgreiche Kundenpräsentationen',
        subtitle: 'Vertrieb',
        description: 'Ein Beispieltext für diese Kundenpräsentation...',
        image: KanufahrtDschungel,
        alternativeText: 'Ein Beispielbild',
        achievedAt: '2023-10-18T14:00:00Z',
        achievedText: 'Kunden begeistert! Erfolgreiche Präsentation.',
        actionType: ActionTypes.INFO,
        achievementType: AchievementType.TIERED,
        maxSteps: 15,
        currentStep: 15,
        achievementState: AchievementState.COMPLETED,
        newAchievement: true,
    },
    {
        name: '30 Tage kontinuierliche Code-Optimierung',
        subtitle: 'Softwareentwicklung',
        description: 'Ein Beispieltext für diese Code-Optimierung...',
        image: ExampleStreakImageRecord,
        alternativeText: 'Ein Beispielbild',
        achievedAt: '2023-11-02T11:10:00Z',
        achievedText: 'Optimaler Code! Herausragende Leistung im Entwicklerteam.',
        actionType: ActionTypes.WAIT,
        achievementType: AchievementType.STREAK,
        maxSteps: 30,
        currentStep: 30,
        achievementState: AchievementState.INACTIVE,
    },
    {
        name: '25 behandelte Support-Anfragen',
        subtitle: 'Kundenbetreuung',
        description: 'Ein Beispieltext für diese Support-Anfragen...',
        image: SequenceExample04,
        alternativeText: 'Ein Beispielbild',
        achievedAt: '2023-10-12T17:30:00Z',
        achievedText: 'Exzellenter Kundenservice! Alle Anfragen erfolgreich bearbeitet.',
        actionType: ActionTypes.APPOINTMENT,
        achievementType: AchievementType.SEQUENTIAL,
        maxSteps: 4,
        currentStep: 0,
        achievementState: AchievementState.INACTIVE,
    },
    {
        name: '40 veröffentlichte Artikel',
        subtitle: 'Content-Erstellung',
        description: 'Ein Beispieltext für diese Artikelveröffentlichungen...',
        image: KanufahrtDschungel,
        alternativeText: 'Ein Beispielbild',
        achievedAt: '2023-09-28T08:45:00Z',
        achievedText: 'Kreativität am Werk! 40 Artikel erfolgreich veröffentlicht.',
        actionType: ActionTypes.ACTION,
        achievementType: AchievementType.TIERED,
        maxSteps: 40,
        currentStep: 40,
        achievementState: AchievementState.COMPLETED,
    },
    {
        name: '50 Stunden interne Schulungen geleitet',
        subtitle: 'Weiterbildung',
        description: 'Ein Beispieltext für diese internen Schulungen...',
        image: SequenceExample00,
        alternativeText: 'Ein Beispielbild',
        achievedAt: '2023-11-08T13:15:00Z',
        achievedText: 'Wissensvermittlung pur! Erfolgreiche Leitung von Schulungen.',
        actionType: ActionTypes.INFO,
        achievementType: AchievementType.SEQUENTIAL,
        maxSteps: 50,
        currentStep: 0,
        achievementState: AchievementState.INACTIVE,
    },
    {
        name: '12 abgeschlossene Schulungseinheiten',
        subtitle: 'Weiterbildung',
        description: 'Ein Beispieltext für diese Schulungseinheit...',
        image: KanufahrtDschungel,
        alternativeText: 'Ein Beispielbild',
        achievedAt: '2023-11-05T15:45:00Z',
        achievedText: 'Herzlichen Glückwunsch! Schulung erfolgreich abgeschlossen.',
        actionType: ActionTypes.WAIT,
        achievementType: AchievementType.TIERED,
        maxSteps: 12,
        currentStep: 8,
        achievementState: AchievementState.ACTIVE,
    },
    {
        name: '25 Stunden Teamzusammenarbeit',
        subtitle: 'Kollaboration',
        description: 'Ein Beispieltext für diese Teamzusammenarbeit...',
        image: ExampleStreakImage,
        alternativeText: 'Ein Beispielbild',
        achievedAt: '2023-10-02T09:20:00Z',
        achievedText: 'Teamwork macht den Traum wahr! Tolle Zusammenarbeit.',
        actionType: ActionTypes.APPOINTMENT,
        achievementType: AchievementType.STREAK,
        maxSteps: 25,
        currentStep: 20,
        achievementState: AchievementState.ACTIVE,
    },
    {
        name: '20 erfolgreiche Kundenpräsentationen',
        subtitle: 'Vertrieb',
        description: 'Ein Beispieltext für diese Kundenpräsentation...',
        image: KanufahrtDschungel,
        alternativeText: 'Ein Beispielbild',
        achievedAt: '2023-10-18T14:00:00Z',
        achievedText: 'Kunden begeistert! Erfolgreiche Präsentation.',
        actionType: ActionTypes.INFO,
        achievementType: AchievementType.TIERED,
        maxSteps: 20,
        currentStep: 20,
        achievementState: AchievementState.COMPLETED,
        newAchievement: true,
    },
    {
        name: '35 Tage kontinuierliche Code-Optimierung',
        subtitle: 'Softwareentwicklung',
        description: 'Ein Beispieltext für diese Code-Optimierung...',
        image: ExampleStreakImageRecord,
        alternativeText: 'Ein Beispielbild',
        achievedAt: '2023-11-02T11:10:00Z',
        achievedText: 'Optimaler Code! Herausragende Leistung im Entwicklerteam.',
        actionType: ActionTypes.WAIT,
        achievementType: AchievementType.STREAK,
        maxSteps: 35,
        currentStep: 0,
        achievementState: AchievementState.INACTIVE,
    },
    {
        name: '30 behandelte Support-Anfragen',
        subtitle: 'Kundenbetreuung',
        description: 'Ein Beispieltext für diese Support-Anfragen...',
        image: SequenceExample04,
        alternativeText: 'Ein Beispielbild',
        achievedAt: '2023-10-12T17:30:00Z',
        achievedText: 'Exzellenter Kundenservice! Alle Anfragen erfolgreich bearbeitet.',
        actionType: ActionTypes.APPOINTMENT,
        achievementType: AchievementType.SEQUENTIAL,
        maxSteps: 5,
        currentStep: 0,
        achievementState: AchievementState.INACTIVE,
    },
    {
        name: '45 veröffentlichte Artikel',
        subtitle: 'Content-Erstellung',
        description: 'Ein Beispieltext für diese Artikelveröffentlichungen...',
        image: KanufahrtDschungel,
        alternativeText: 'Ein Beispielbild',
        achievedAt: '2023-09-28T08:45:00Z',
        achievedText: 'Kreativität am Werk! 45 Artikel erfolgreich veröffentlicht.',
        actionType: ActionTypes.ACTION,
        achievementType: AchievementType.TIERED,
        maxSteps: 45,
        currentStep: 45,
        achievementState: AchievementState.COMPLETED,
    },
];

export { achievements };
