import { Appointment, AppointmentTypes } from '../../../types/lernfair/Appointment';

export const appointmentsData: Appointment[] = [
    {
        id: 108,
        title: 'Test TD',
        description: 'Testbeschreibung TD',
        start: '2023-02-14T16:00:00.000Z',
        duration: 15,
        subcourseId: 1,
        matchId: null,
        meetingLink: null,
        appointmentType: AppointmentTypes.GROUP,
    },
    {
        id: 109,
        title: 'Test TD',
        description: 'Testbeschreibung TD',
        start: '2023-02-15T16:00:00.000Z',
        duration: 15,
        subcourseId: 1,
        matchId: null,
        meetingLink: null,
        appointmentType: AppointmentTypes.GROUP,
    },
    {
        id: 110,
        title: 'Test TD',
        description: 'Testbeschreibung TD',
        start: '2023-02-16T16:00:00.000Z',
        duration: 15,
        subcourseId: 1,
        matchId: null,
        meetingLink: null,
        appointmentType: AppointmentTypes.GROUP,
    },
    {
        id: 111,
        title: 'Test TD',
        description: 'Testbeschreibung TD',
        start: '2023-03-14T16:00:00.000Z',
        duration: 15,
        subcourseId: 1,
        matchId: null,
        meetingLink: null,
        appointmentType: AppointmentTypes.GROUP,
    },
    {
        id: 112,
        title: 'Test TD',
        description: 'Testbeschreibung TD',
        start: '2023-03-14T16:00:00.000Z',
        duration: 15,
        subcourseId: 1,
        matchId: null,
        meetingLink: null,
        appointmentType: AppointmentTypes.GROUP,
    },
    {
        id: 113,
        title: 'Test TD',
        description: 'Testbeschreibung TD',
        start: '2023-03-14T16:00:00.000Z',
        duration: 15,
        subcourseId: 1,
        matchId: null,
        meetingLink: null,
        appointmentType: AppointmentTypes.GROUP,
    },
    {
        id: 114,
        title: 'Test TD',
        description: 'Testbeschreibung TD',
        start: '2023-07-14T16:00:00.000Z',
        duration: 15,
        subcourseId: 1,
        matchId: null,
        meetingLink: null,
        appointmentType: AppointmentTypes.GROUP,
    },
    {
        id: 115,
        title: 'Test TD',
        description: 'Testbeschreibung TD',
        start: '2023-07-14T16:00:00.000Z',
        duration: 15,
        subcourseId: 1,
        matchId: null,
        meetingLink: null,
        appointmentType: AppointmentTypes.GROUP,
    },
    {
        id: 116,
        title: 'Test TD',
        description: 'Testbeschreibung TD',
        start: '2024-01-14T16:00:00.000Z',
        duration: 15,
        subcourseId: 1,
        matchId: null,
        meetingLink: null,
        appointmentType: AppointmentTypes.GROUP,
    },
    {
        id: 117,
        title: 'Test TD',
        description: 'Testbeschreibung TD',
        start: '2024-02-14T16:00:00.000Z',
        duration: 15,
        subcourseId: 1,
        matchId: null,
        meetingLink: null,
        appointmentType: AppointmentTypes.GROUP,
    },
];
